IF OBJECT_ID('FACT', 'U') IS NOT NULL
BEGIN
    DELETE FROM FACT;
END
GO

IF OBJECT_ID('DIM_Product', 'U') IS NOT NULL
BEGIN
    DELETE FROM DIM_Product;
END
GO

IF OBJECT_ID('DIM_Employee', 'U') IS NOT NULL
BEGIN
    DELETE FROM DIM_Employee;
END
GO

IF OBJECT_ID('DIM_Customer', 'U') IS NOT NULL
BEGIN
    DELETE FROM DIM_Customer;
END
GO

IF OBJECT_ID('DIM_Date', 'U') IS NOT NULL
BEGIN
    DELETE FROM DIM_Date;
END
GO

IF OBJECT_ID('DIM_Ship', 'U') IS NOT NULL
BEGIN
    DELETE FROM DIM_Ship;
END
GO

IF OBJECT_ID('DIM_Category', 'U') IS NOT NULL
BEGIN
    DELETE FROM DIM_Category;
END
GO

IF OBJECT_ID('DIM_Supplier', 'U') IS NOT NULL
BEGIN
    DELETE FROM DIM_Supplier;
END
GO

IF OBJECT_ID('DIM_Location', 'U') IS NOT NULL
BEGIN
    DELETE FROM DIM_Location;
END
GO
