IF OBJECT_ID('NULL_FACT', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_FACT;
END
GO

IF OBJECT_ID('NULL_Product', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_Product;
END
GO

IF OBJECT_ID('NULL_Employee', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_Employee;
END
GO

IF OBJECT_ID('NULL_Customer', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_Customer;
END
GO

IF OBJECT_ID('NULL_Date', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_Date;
END
GO

IF OBJECT_ID('NULL_Ship', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_Ship;
END
GO

IF OBJECT_ID('NULL_Category', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_Category;
END
GO

IF OBJECT_ID('NULL_Supplier', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_Supplier;
END
GO

IF OBJECT_ID('NULL_Location', 'U') IS NOT NULL
BEGIN
    DELETE FROM NULL_Location;
END
GO
